### ISSUE TITLE
Add to PATH on install.

### ISSUE THREAD

**Issue by ChildishGiant** [megagrump/yuema#1]
It'd be nice for an option to add yuema to usr/bin on install so that the source directory can be deleted

**Comment by megagrump** [comment]
The way it's supposed to be used is having the binary, the `lib` directory and user code files in the same directory hierarchy. System-wide installation of the binary does not make sense at this point in time and would create a lot of problems that I don't want to deal with right now.

It's not supposed to be an installable package that you can run a number of games with; it's supposed to be packaged individually for every game, including the binary and the core library.

**Comment by ChildishGiant** [comment]
Ah okay. I assumed it was to be installed system-wide. With the updated readme I've got it all working. Thanks very much :smile:

**Comment by megagrump** [comment]
Happy to hear that!

The goal is for every project to be as self-contained as possible, and to make it easy to distribute your game for game jams etc., without having to worry about package installation or possible version conflicts/library incompatibilities.

The examples are a special case, that's why they must be run in this specific way.
